"""empty message

Revision ID: 59b5c2365bbe
Revises: 97da4e58f8e2
Create Date: 2019-04-28 03:02:11.108890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59b5c2365bbe'
down_revision = '97da4e58f8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_id')
    op.add_column('book_recommend_category', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'book_recommend_category', ['name'])
    op.drop_column('book_recommend_category', 'rc_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_recommend_category', sa.Column('rc_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'book_recommend_category', type_='unique')
    op.drop_column('book_recommend_category', 'subject_id')
    op.create_table('user_id',
    sa.Column('rc_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rc_id'], ['book_recommend_category.rc_id'], name='user_id_ibfk_1'),
    sa.PrimaryKeyConstraint('rc_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
