"""empty message

Revision ID: 97da4e58f8e2
Revises: 
Create Date: 2019-04-25 00:53:22.388646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97da4e58f8e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('lib_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'lib_id')
    # ### end Alembic commands ###
